name: Protobuf schema deployment

on:
  push:
    branches:
      - master

jobs:
  schema-registration:
    name: Protobuf schema registration check

    runs-on: ubuntu-latest

    env:
      SCHEMA_REGISTRY_KEY: ${{ secrets.SCHEMA_REGISTRY_KEY }}
      SCHEMA_REGISTRY_SECRET: ${{ secrets.SCHEMA_REGISTRY_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f gh-action/requirements.txt ]; then pip install -r gh-action/requirements.txt; fi
      - id: files
        name: List changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: Compatability Check
        run: |
          python ./gh-action/proto_check_action.py -r ${{ secrets.SCHEMA_REGISTRY }} -f ${{ steps.files.outputs.added_modified }}
      - name: Schema registration
        run: |
          python ./gh-action/proto_register_action.py -r ${{ secrets.SCHEMA_REGISTRY }} -f ${{ steps.files.outputs.added_modified }}

  schema-deployemnt:
    name: Protobuf Schema Deployemt
    needs: schema-registration

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish JAR
        run: |
          ./gradlew proto-repo:publishMavenJavaPublicationToGitHubPackagesRepository \
            -Pminor.version=${{ env.GITHUB_RUN_ID }} \
            -Ppatch.version=${{ env.GITHUB_RUN_NUMBER }
