name: Protobuf schema check

on:
  push:

jobs:
  schema-check:
    name: Protobuf schema compatability check

    runs-on: ubuntu-latest

    env:
      SCHEMA_REGISTRY_KEY: ${{ secrets.SCHEMA_REGISTRY_KEY }}
      SCHEMA_REGISTRY_SECRET: ${{ secrets.SCHEMA_REGISTRY_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f gh-action/requirements.txt ]; then pip install -r gh-action/requirements.txt; fi
      - id: files
        name: List changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Compatability Check
        run: python ./gh-action/proto-check-action.py -r=${{ secrets.SCHEMA_REGISTRY_SECRET }} -f="${{ steps.files.outputs.added_modified }}"
